all:
  children:
    hk:
      hosts:
        hk.yunplus.io
      vars:
        ansible_ssh_user: root
        # ansible_ssh_key_file: ~/.ssh/fpm
        ansible_ssh_key: "{{ lookup('vars', 'fpmsshkey') }}"
        ansible_python_interpreter: /usr/bin/python3