---
# more detail in the url: https://docs.ansible.com/ansible/2.8/modules/docker_container_module.html?highlight=docker
- name: update the docker containers
  hosts: hk
  remote_user: root
  tasks:
  - name: pull image
    docker_image:
      name: yfsoftcom/coder-kit
      tag: "{{ tag }}"
      source: pull
      state: present
    register: pull

  - name: checkout pull
    debug: var=pull

  - name: re-create containers
    docker_container:
      name: coder-kit
      image: yfsoftcom/coder-kit
      tag: "{{tag}}"
      # state: present
      recreate: yes
      # restart: yes
      ports:
        - "18080:80"
        
    register: recreate
  - name: checkout recreate
    debug: var=recreate
