version: '3.0'
services:
  proxy:
    container_name: proxy
    restart: always
    image: nginx:1.18.0-alpine
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./devops/ssl/conf.d:/etc/nginx/conf.d
     - ./devops/ssl/html:/usr/share/nginx/html
     - ./devops/ssl/certs:/etc/letsencrypt