# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ⚽ Build Image

on:
  push:
    branches:
      - main
    paths:
      - 'web/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v2
      # 使用Docker官方制作的action
      # https://github.com/marketplace/actions/build-and-push-docker-images
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_NAME }}
      #     password: ${{ secrets.DOCKER_PASS }}
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: yfsoftcom/coder-kit:latest
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

      - name: update the container
        id: update_container
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          playbookName: 'devops/site.yaml'
          inventoryFile: 'devops/inventory-server.yaml'
          keyFile: 'devops/ansible-deploy-encrypt.pem'
          keyFileVaultPass: '{{ secret.FPM_PRIVATE_SSH_KEY_ENCRYPT }}'