
name: CI
on:
  push:
    branches:
      - main
    # paths:
    #   - 'web/src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: cd web/ && yarn && yarn run build
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-shanghai.aliyuncs.com"
        access-key-id: ${{ secrets.ALICLOUD_ACCESS_KEY }}
        access-key-secret: ${{ secrets.ALICLOUD_SECRET_KEY }}
    - run: cd web/build && ossutil cp -rf . oss://bucket-website-blog-yunjiaiot-cn
    